# Generated by Django 4.0.1 on 2022-02-13 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancarriere',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mort_tuer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Monture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('mouvement', models.PositiveIntegerField(blank=True, null=True)),
                ('capacite_combat', models.PositiveIntegerField(blank=True, null=True)),
                ('capacité_tir', models.PositiveIntegerField(blank=True, null=True)),
                ('force', models.PositiveIntegerField(blank=True, null=True)),
                ('endurance', models.PositiveIntegerField(blank=True, null=True)),
                ('point_blessure', models.PositiveIntegerField(blank=True, null=True)),
                ('initiative', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_attaque', models.PositiveIntegerField(blank=True, null=True)),
                ('dexterite', models.PositiveIntegerField(blank=True, null=True)),
                ('commandement', models.PositiveIntegerField(blank=True, null=True)),
                ('intelligence', models.PositiveIntegerField(blank=True, null=True)),
                ('calme', models.PositiveIntegerField(blank=True, null=True)),
                ('force_mentale', models.PositiveIntegerField(blank=True, null=True)),
                ('sociabilite', models.PositiveIntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
            options={
                'verbose_name': 'Monture',
                'verbose_name_plural': 'Montures',
            },
        ),
    ]
