# Generated by Django 4.0.1 on 2022-02-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_plancarriere_nom_player_mort_tuer_monture'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='apprentissage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competence',
            name='cout_xp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
